apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenge
spec:
  replicas: 3
  selector:
    matchLabels:
      app: celonischallenge
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: celonischallenge
    spec:
      containers:
        - name: challenge
          image: challenge-11
          resources: {}
          imagePullPolicy: IfNotPresent
          ports:
           - containerPort: 8080
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: challenge-secrets
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: challenge-secrets
                  key: DB_PASSWORD
            - name: AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: challenge-secrets
                  key: AUTH_SECRET
---
kind: Service
apiVersion: v1
metadata:
  name: postgres-db-svc
spec:
  type: ExternalName
  externalName: 127.0.0.1
apiVersion: v1
---
kind: Service
apiVersion: v1
metadata:
  name: challenge
spec:
  type: NodePort
  selector:
    app: celonischallenge
  ports:
  - protocol: TCP
    nodePort: 30163
    port: 33333
    targetPort: 8080
---
apiVersion: v1
kind: Secret
metadata:
  name: challenge-secrets
data:
  DB_USER: Y2hhbGxlbmdl
  DB_PASSWORD: cGFzc3dvcmQxMjM=
  AUTH_SECRET: dG90YWxseV9zZWNyZXQ=
