apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenge
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - image: flxw/challenge
        name: challenge
        resources: {}
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8086
status: {}
