swagger: '2.0'
info:
  title: MarsGate API
  description: This is the specification for the MarsGate API. MarsGate is an application management tool for applying for the "Free ticket to mars lottery". It expects a cookie called MARSGATEAUTH that proves whether a user is logged in or not. It authorizes the request to perform actions on the user's applications.
  version: 1.0.0
basePath: /api/v1
schemes:
  - https
paths:
  /applications:
    get:
      summary: Get all applications for the current user
      description: This endpoint returns all applications, irrespective of their state for the current user. The returned list is empty if there aren't any. Parts of an application can be null, since these have not been submitted yet
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Application'
        401:
          description: Unauthorized
      produces:
        - application/json
  /application:
    post:
      summary: Create a new application for the current user
      description: Create a new, empty application for the current user. Returns the application ID
      responses:
        200:
          description: OK
          schema:
            type: string
            format: uuid
        401:
          description: Unauthorized - accessing without cookie
      produces:
        - application/json
  /application/{id}:
    parameters:
      - name: id
        in: path
        type: string
        format: uuid
        description: Application ID in UUID format
        required: true
    get:
      summary: Get an application
      description: Gets the specified application, if it belongs to the current user. Parts of the application can be null, since these have not been submitted yet
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Application'
        404:
          description: Application not present or access forbidden (to prevent snooping)
        401:
          description: Unauthorized - accessing without cookie
    delete:
      summary: Cancel and delete an application
      description: Cancels and deletes an application, if it belongs to the current user
      responses:
        204:
          description: OK
        404:
          description: Application not present or access forbidden (to prevent snooping)
        401:
          description: Unauthorized - accessing without cookie
    
  /application/{id}/cv:
    parameters:
      - name: id
        in: path
        type: string
        format: uuid
        description: Application ID in UUID format
        required: true
    put:
      summary: Set an application's CV
      description: Set the application's CV, overriding any previously existing CV
      parameters:
        - name: cv
          in: body
          schema:
            $ref: '#/definitions/CV'
      responses:
        204:
          description: OK
        404:
          description: Application not present or access forbidden (to prevent snooping)
        401:
          description: Unauthorized - accessing without cookie
  /application/{id}/details:
    parameters:
      - name: id
        in: path
        type: string
        format: uuid
        description: Application ID in UUID format
        required: true
    put:
      summary: Set an application's details
      description: Set the application's details, overriding any previously existing detail
      parameters:
        - name: cv
          in: body
          schema:
            $ref: '#/definitions/CV_Details'
      responses:
        204:
          description: OK
        404:
          description: Application not present or access forbidden (to prevent snooping)
        401:
          description: Unauthorized - accessing without cookie
  /application/{id}/essay:
    parameters:
      - name: id
        in: path
        type: string
        format: uuid
        description: Application ID in UUID format
        required: true
    put:
      summary: Set an application's essay
      description: Set the application's essay, overriding any previously existing essay
      parameters:
        - name: cv
          in: body
          schema:
            type: string
      responses:
        204:
          description: OK
        404:
          description: Application not present or access forbidden (to prevent snooping)
        401:
          description: Unauthorized - accessing without cookie
  /application/{id}/submit:
    parameters:
      - name: id
        in: path
        type: string
        format: uuid
        description: Application ID in UUID format
        required: true
    post:
      summary: Submit an application
      description: Submit the application if it is complete and belongs to the user
      responses:
        204:
          description: OK
        403:
          description: The application is incomplete and can not be submitted
        404:
          description: Application not present or access forbidden (to prevent snooping)
        401:
          description: Unauthorized - accessing without cookie

securityDefinitions:
   'User Authentication Cookie':
     type: apiKey
     in: header
     name: MARSGATEAUTH
     
security:
  - 'User Authentication Cookie': []

definitions:
  Application:
    type: object
    properties:
      id:
        type: string
        format: uuid
      cv:
        $ref: '#/definitions/CV'
      details:
        $ref: '#/definitions/CV_Details'
      essay:
        type: string
  CV:
    type: array
    description: A CV consists of multiple events on a timeline
    items:
      $ref: '#/definitions/CV_Event'
  CV_Event:
    type: object
    properties:
      start:
        type: string
        format: date
        description: Start date of the tenure
      end:
        type: string
        format: date
        description: End date of the tenure
      position:
        type: string
        description: Role during the tenure
      employer:
        type: string
        description: Name of the employer during the tenure
      location:
        type: string
        description: Location of workplace
      description:
        type: string
        description: Description of duties during the tenure
  CV_Details:
    type: object
    description: Metadata about the application like age and address
    properties:
      birthday:
        type: string
        format: date
      firstnames:
        type: array
        description: If the applicant has more than one first name, this array has multiple items
        items:
          type: string
      lastname:
        description: The surname, or family name
        type: string
      address:
        $ref: '#/definitions/Address'
      status:
        type: string
  Address:
    type: object
    properties:
      street:
        type: string
      number:
        type: integer
      postcode:
        type: integer
      city:
        type: string
      country:
        type: string
      co:
        description: The C/O information, optional, in case the lastname is not on the bell tag
        type: string